// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.5
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic",prev:"",next:"",duration:20*100,delay:20*100,width:400,height:640,autoPlay:false,autoPlayVideo:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"parallax",controls:true,controlsThumb:false,responsive:1,fullScreen:true,gestures:2,onBeforeStep:0,images:[{src:"./flyerg17page001.jpg",title:"Sozi-RtmForTheKids_1-0-2_01"},{src:"./flyerg17page002.jpg",title:"Sozi-RtmForTheKids_1-0-2_02"},{src:"./flyerg17page003.jpg",title:"Sozi-RtmForTheKids_1-0-2_03"},{src:"./flyerg17page004.jpg",title:"Sozi-RtmForTheKids_1-0-2_04"}]});